# Gradient Descent and Linear Regression in PyTorch

importing libraries

In [1]:
import torch
import numpy as np

Inputs ( temp, rainfall, humidity) and targets (yelid of apples and oranges)

In [2]:
inputs = np.array([[73,67,43],
                   [91,88,64],
                   [87,134,58],
                   [102,43,37],
                   [69,96,70]], dtype=np.float32)

target = np.array([[56,70],
                   [81,101],
                   [119,133],
                   [22,37],
                   [103,119]],dtype=np.float32)

converting inputs and targets into tensors

In [3]:
inputs = torch.from_numpy(inputs)
target = torch.from_numpy(target)

print(inputs)
print(target)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


Linear regression model

In [4]:
w = torch.randn(2,3,requires_grad=True)
b = torch.randn(2, requires_grad=True)

print(w)
print(b)

tensor([[ 0.8347, -0.8753, -0.2540],
        [ 0.3690, -0.6541,  1.3285]], requires_grad=True)
tensor([-1.9482,  0.0925], requires_grad=True)


In [5]:
model = lambda x : x @ w.t() + b

In [6]:
# generating predictions

predicts = model(inputs)
print(predicts)

tensor([[-10.5870,  40.3316],
        [-19.2795,  61.1365],
        [-61.3583,  21.6007],
        [ 36.1504,  58.7603],
        [-46.1691,  55.7565]], grad_fn=<AddBackward0>)


In [7]:
# comparing with targets

print(target)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


Loss function

In [8]:
def mse(t1,t2):
    diff = t1 - t2
    return torch.sum(diff * diff)/diff.numel()

In [9]:
loss = mse(predicts,target)
print(loss)

tensor(8882.2939, grad_fn=<DivBackward0>)


In [10]:
# compute gradients
loss.backward()

In [11]:
w.grad,b.grad

(tensor([[ -7705.3579, -10233.1416,  -5932.0371],
         [ -3525.8726,  -5111.7920,  -2782.0159]]),
 tensor([-96.4487, -44.4829]))

In [12]:
lr = 1e-5
with torch.no_grad():
    w -= w.grad * lr
    b -= b.grad * lr

w,b

(tensor([[ 0.9117, -0.7730, -0.1947],
         [ 0.4043, -0.6030,  1.3563]], requires_grad=True),
 tensor([-1.9473,  0.0929], requires_grad=True))

In [13]:
# Now lets verify loss is lowered or not
predicts = model(inputs)
loss = mse(predicts,target)
print(loss)

tensor(6644.0376, grad_fn=<DivBackward0>)


When you done with computation of gradient and again you want to do gradient calculation set grads to zero or else it will add new grads to previous ones

In [14]:
w.grad.zero_()
b.grad.zero_()

w.grad,b.grad

(tensor([[0., 0., 0.],
         [0., 0., 0.]]),
 tensor([0., 0.]))

## Training the model using gradient descent

As seen above, we reduce the loss and improve our model using the gradient descent optimization algorithm. Thus, we can train the model using the following steps:

1. Generate predictions
2. Calculate the loss
3. Compute gradients w.r.t the weights and biases
4. Adjust the weights by subtracting a small quantity proportional to the gradient
5. Reset the gradients to zero

In [15]:
# Generate predictions
predicts = model(inputs)
print(predicts)

tensor([[  4.4458,  47.5271],
        [  0.5350,  70.6243],
        [-37.5007,  33.1320],
        [ 50.6059,  65.5845],
        [-26.8752,  65.0446]], grad_fn=<AddBackward0>)


In [16]:
# Calculate the loss
loss = mse(predicts,target)
print(loss)

tensor(6644.0376, grad_fn=<DivBackward0>)


In [17]:
# Compute gradients w.r.t weights and biases
loss.backward()

In [18]:
# Adjusting weights by subtracting a small quantity proportional to the gradient
lr = 1e-5
with torch.no_grad():
    w -= w.grad * lr
    b -= b.grad * lr
    w.grad.zero_()
    b.grad.zero_()

With new weights and biases lets see how loss is changed.

In [19]:
predicts = model(inputs)
loss = mse(predicts, target)
print(loss)

tensor(5127.5303, grad_fn=<DivBackward0>)


## Train the model for multiple epochs

In [20]:
lr = 1e-5
while loss > 0.6:
    predicts = model(inputs)
    loss = mse(predicts, target)
    loss.backward()
    lr = 1e-5
    with torch.no_grad():
        w -= w.grad * lr
        b -= b.grad * lr
        w.grad.zero_()
        b.grad.zero_()

In [21]:
# Lets verify loss is lowered or not
predicts = model(inputs)
loss = mse(predicts, target)
print(loss)

tensor(0.5997, grad_fn=<DivBackward0>)


In [22]:
predicts,target

(tensor([[ 56.8589,  70.2928],
         [ 82.2386, 100.9149],
         [119.1072, 132.4281],
         [ 21.2238,  36.8656],
         [101.5075, 119.6675]], grad_fn=<AddBackward0>),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.],
         [ 22.,  37.],
         [103., 119.]]))

## Using built-in PyTorch library for linear regression

In [23]:
import torch.nn as nn

In [24]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70], 
                   [74, 66, 43], 
                   [91, 87, 65], 
                   [88, 134, 59], 
                   [101, 44, 37], 
                   [68, 96, 71], 
                   [73, 66, 44], 
                   [92, 87, 64], 
                   [87, 135, 57], 
                   [103, 43, 36], 
                   [68, 97, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
target = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119],
                    [57, 69], 
                    [80, 102], 
                    [118, 132], 
                    [21, 38], 
                    [104, 118], 
                    [57, 69], 
                    [82, 100], 
                    [118, 134], 
                    [20, 38], 
                    [102, 120]], 
                   dtype='float32')

inputs = torch.from_numpy(inputs)
target = torch.from_numpy(target)

# Dataset and data loader

In [25]:
from torch.utils.data import TensorDataset,DataLoader
import torch.nn.functional as F

In [26]:
train_ds = TensorDataset(inputs,target)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

The `TensirDataset` allow us to access a small section of the training data using the training data using the array indexing notation (`[0:3]` in the above code). It returns a tuple with two elements. The first element contains the input variables for the selected rows, and the second contains the targets.

In [27]:
# Defining a batch loader
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

In [28]:
for xb,yb in train_dl:
    print(xb)
    print(yb)
    break

tensor([[ 69.,  96.,  70.],
        [ 91.,  88.,  64.],
        [ 68.,  96.,  71.],
        [ 73.,  66.,  44.],
        [ 87., 135.,  57.]])
tensor([[103., 119.],
        [ 81., 101.],
        [104., 118.],
        [ 57.,  69.],
        [118., 134.]])


## nn.Linear
instead of initializing weights and biases manually, we can define the model using the `nn.Linear` class from PyTorch which does it automatically

In [29]:
# Defining model

model = nn.Linear(3,2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.1958, -0.0320,  0.2164],
        [ 0.0178, -0.1479,  0.1627]], requires_grad=True)
Parameter containing:
tensor([-0.5366,  0.0494], requires_grad=True)


In [30]:
# Parameters 
list(model.parameters())

[Parameter containing:
 tensor([[-0.1958, -0.0320,  0.2164],
         [ 0.0178, -0.1479,  0.1627]], requires_grad=True),
 Parameter containing:
 tensor([-0.5366,  0.0494], requires_grad=True)]

In [31]:
# Generate predictions using model

predicts = model(inputs)
print(predicts)

tensor([[ -7.6661,  -1.5720],
        [ -7.3170,  -0.9433],
        [ -9.3051,  -8.7958],
        [-13.8742,   1.5179],
        [ -1.9673,  -1.5417],
        [ -7.8299,  -1.4063],
        [ -7.0686,  -0.6327],
        [ -9.2845,  -8.6154],
        [-13.7104,   1.3522],
        [ -1.5551,  -1.3968],
        [ -7.4177,  -1.2614],
        [ -7.4808,  -0.7776],
        [ -9.5536,  -9.1064],
        [-14.2864,   1.3730],
        [ -1.8035,  -1.7074]], grad_fn=<AddmmBackward0>)


Instead of defining loss function manually we can use built-in loss function `mse_loss`

In [32]:
loss_fn = F.mse_loss

In [33]:
loss = loss_fn(model(inputs),target)
print(loss)

tensor(9177.6045, grad_fn=<MseLossBackward0>)


## Optimizer

instead of manually manipulating the model's weights and biases using gradients, we can use the optimizer `optim.SGD`. SGD is short for 'stochastic gradient descent'. The term stochastic indicates that samples are selected in random batches instead of as a single group.

In [34]:
# Define optimizer

opt = torch.optim.SGD(model.parameters(),lr=1e-5)

NOTE: `model.parameters()` is passses as an argument to `optim.SGD` so that the optimizer knows which matrices should be modified during the update step. Also, we can specify a learning rate that controls the amount by which the parameters are modified

## Training the model 

We are now ready to train the model. We'll follow the same process to implement gradient descent:

1. Generate predictions
2. Calculate the loss
3. Compute gradients w.r.t the weights and biases
4. Adjust the weights by subtracting a small quantity proportional to the gradient
5. Reset the gradients to zero

The only change is that we'll work on batch of data instead of processing the entire training data in every iteration. Let's define a utility function `fit` that trains the model for a given number of epoch

In [35]:
# utility function to train modle
def fit(num_epoch,model, loss_fn, opt, train_dl):

    # Repeat for given number of epochs
    for epoch in range(num_epoch):

        # Train with batch of data
        for xb,yb in train_dl:

            # 1. Generate predictions
            predicts = model(xb)

            # 2. Calculate loss
            loss = loss_fn(predicts,yb)

            # 3. Compute gradients
            loss.backward()

            # 4. Update parameters using gradients
            opt.step()

            # 5. Reset gradients to zero
            opt.zero_grad()

        # Printing the process
        if((epoch+1)%10 == 0):
            print(f'Epoch {epoch+1}/{num_epoch} --------- loss : {loss.item()}')


Some things to note above:

1. We use the data loader defined earlier to get batches of data for every iteration
2. Instead of updating parameters (weights and biases) manually, we use `opt.step` to perform the update and `opt.zero_grad` to reset the gradients to zero.
3. We've also addad a log statement that prints the loss from the last batch of data for every $10^{th}$ epoch to track the training progress. `loss.item()` returns the actual value stored in the loss tensor.

Let's train the model for 200 epochs.

In [36]:
fit(200,model,loss_fn,opt,train_dl)

Epoch 10/200 --------- loss : 543.476318359375
Epoch 20/200 --------- loss : 124.69002532958984
Epoch 30/200 --------- loss : 96.85050201416016
Epoch 40/200 --------- loss : 61.642913818359375
Epoch 50/200 --------- loss : 63.903038024902344
Epoch 60/200 --------- loss : 61.39103317260742
Epoch 70/200 --------- loss : 46.685543060302734
Epoch 80/200 --------- loss : 27.779117584228516
Epoch 90/200 --------- loss : 34.26868438720703
Epoch 100/200 --------- loss : 21.014400482177734
Epoch 110/200 --------- loss : 5.479875087738037
Epoch 120/200 --------- loss : 13.077142715454102
Epoch 130/200 --------- loss : 11.66965103149414
Epoch 140/200 --------- loss : 8.120980262756348
Epoch 150/200 --------- loss : 8.627596855163574
Epoch 160/200 --------- loss : 4.261711120605469
Epoch 170/200 --------- loss : 5.70742654800415
Epoch 180/200 --------- loss : 1.9382864236831665
Epoch 190/200 --------- loss : 3.3390235900878906
Epoch 200/200 --------- loss : 4.266870498657227


Let's generate predictions using out model and verify that they're close to our targets.

In [37]:
# Generate predictions
predicts = model(inputs)
predicts

tensor([[ 57.0725,  70.6833],
        [ 81.5809,  99.1757],
        [119.1362, 135.2701],
        [ 21.9023,  39.3514],
        [100.3285, 115.2197],
        [ 55.8385,  69.5995],
        [ 81.3343,  99.0166],
        [119.3856, 135.7386],
        [ 23.1363,  40.4352],
        [101.3158, 116.1444],
        [ 56.8258,  70.5243],
        [ 80.3470,  98.0918],
        [119.3828, 135.4291],
        [ 20.9150,  38.4267],
        [101.5624, 116.3035]], grad_fn=<AddmmBackward0>)

In [38]:
# Comparing with targets
target

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])

Indeed, the predictions are quite close to our targets. We jave a trained a reasonably good model to predict crop yeilds for apples and oranges by looking at the average temparature, rainfall, and humidity in a region. We can use it to make predictions of crop yeilds for new regions by passing a batch containing a single row of input

In [39]:
model(torch.tensor([75,63,44.]))

tensor([53.4929, 67.5010], grad_fn=<AddBackward0>)

The model predicts apples are in ~53 tons per hectare, and oranges are ~67 tons per hectare