# Pytorch basics Tensors and gradients

importing pytorch library


In [1]:
import torch

## Tensor

As it is core pytorch is a library for processing tensors. A tensor is a number, vector, matrix, or any n-dimensional array.

t1 is zero-dimensional tensor

In [2]:
t1 = torch.tensor(5 ,dtype=torch.float32)
print(t1)
print(t1.shape)

tensor(5.)
torch.Size([])


t2 is one-dimensional tensor

In [3]:
t2 = torch.tensor([1.,2.,3.,4.])
print(t2)
print(t2.shape)

tensor([1., 2., 3., 4.])
torch.Size([4])


t3 is two-dimensional tensor

In [4]:
t3 = torch.tensor([[1.,2.,3.,4.],[5.,6.,7.,8.]])
print(t3)
print(t3.shape)

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])
torch.Size([2, 4])


t4 is three-dimensional tensor

In [5]:
t4 = torch.tensor([[[1.,2.,3.],[4.,5.,6.],[7.,8.,9.]],[[10.,11.,12.],[13.,14.,15.],[16.,17.,18.]]])
print(t4)
print(t4.shape)

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]]])
torch.Size([2, 3, 3])


## Tensor operations and gradients

In [6]:
# we can combine tensors with usual arthimatic operations
x = torch.tensor(3.)
w = torch.tensor(4.,requires_grad=True)
b = torch.tensor(5.,requires_grad=True)

y = w * x + b

print("The value of x is ", x)
print("The value of w is ", w)
print("The value of b is ", b)
print("The value of y is ", y)

The value of x is  tensor(3.)
The value of w is  tensor(4., requires_grad=True)
The value of b is  tensor(5., requires_grad=True)
The value of y is  tensor(17., grad_fn=<AddBackward0>)


We can compute derivative of y with respect to w, b as we made requires_grad = True.

In [7]:
#  To compute gradient
y.backward()

# To display gradient

print('dy/dx',x.grad)
print('dy/dw',w.grad)
print('dy/db',b.grad)

dy/dx None
dy/dw tensor(3.)
dy/db tensor(1.)


creating a tensor with fixed value for each element

In [8]:
t5 = torch.full((3,4),2)
print(t5)
print(t5.shape)

tensor([[2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2]])
torch.Size([3, 4])


we can concatinate two tensors but axis 1 dimensions must be same

In [9]:
print(t3.shape)
print(t5.shape)
t6 = torch.cat((t3,t5))

print(t6)
print(t6.shape)

torch.Size([2, 4])
torch.Size([3, 4])
tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]])
torch.Size([5, 4])


We can reshape tensor using reshape function

In [10]:
t7 = t6.reshape(2,2,5)
print(t7)
print(t7.shape)

tensor([[[1., 2., 3., 4., 5.],
         [6., 7., 8., 2., 2.]],

        [[2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.]]])
torch.Size([2, 2, 5])


We can also use special funtions also


In [11]:
t8 = torch.sin(t7)

print(t8)

tensor([[[ 0.8415,  0.9093,  0.1411, -0.7568, -0.9589],
         [-0.2794,  0.6570,  0.9894,  0.9093,  0.9093]],

        [[ 0.9093,  0.9093,  0.9093,  0.9093,  0.9093],
         [ 0.9093,  0.9093,  0.9093,  0.9093,  0.9093]]])


In [12]:
t9 = torch.ones((2,2))

print(t9)
print(t9.shape)

tensor([[1., 1.],
        [1., 1.]])
torch.Size([2, 2])


## Interpoearablity with Numpy

In [13]:
import numpy as np

n1 = np.array([[1,2,3.],[4,5,6]])

print(n1)
print(n1.shape)

[[1. 2. 3.]
 [4. 5. 6.]]
(2, 3)


We can convert numpy array to tensor

In [14]:
t11 = torch.from_numpy(n1)

print(t11)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)


In [15]:
n1.dtype, t11.dtype

(dtype('float64'), torch.float64)

We can convert tensors to numpy array

In [16]:
n2 = t11.numpy()

print(n2)

[[1. 2. 3.]
 [4. 5. 6.]]


Why we need a library like PyTorch since Numpy already provides data structure and utilities for working with multi-dimensional numeric data.

There are two main resaons.


1. $\textbf{Autograd:}$ The ability to automatically compute gradients for tensor operations is essential for training deep learning models.

2. $\textbf{GPU Support:}$ While working with massive datasets and large models, PyTorch tensor operations can be performed efficiently using a Graphical Processing Unit (GPU). Computations that might typically take hours can be completed within minutes using GPUs.
